apiVersion: v2
name: elasticsearch
description: A Helm chart for deploying EFK stack

type: application
version: 1.0.0

dependencies:
  # - name: elasticsearch
  #   alias: elasticsearch
  #   repository: https://helm.elastic.co
  #   version: 8.5.1
  #   condition: elasticsearch.enabled
  # - name: kibana
  #   alias: kibana
  #   repository: https://helm.elastic.co
  #   version: 8.5.1
  #   condition: kibana.enabled
  - name: elasticsearch
    alias: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    version: 22.0.5
    condition: elasticsearch.enabled
  - name: fluent-bit
    alias: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.49.0
    condition: fluent-bit.enabled

maintainers:
  - name: Erik
