apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch-credentials
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secrets-manager-cluster
    kind: ClusterSecretStore
  target:
    name: elasticsearch-master-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ELASTIC_PASSWORD
      remoteRef:
        key: "erik-chatapp/elasticsearch"
        property: ELASTIC_PASSWORD
    - secretKey: username
      remoteRef:
        key: "erik-chatapp/elasticsearch"
        property: ELASTIC_USERNAME
    - secretKey: elasticsearch-password
      remoteRef:
        key: "erik-chatapp/elasticsearch"
        property: ELASTIC_PASSWORD
