apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-prod"
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Install after cert-manager (wave 0-1)
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "work.erikgavrilov@gmail.com"
    privateKeySecretRef:
      name: "letsencrypt-prod"
    solvers:
      - dns01:
          route53: {}
