apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    path: chat-app
    repoURL: "git@gitlab.com:bootcamp1531414/portfolio-gitops.git"
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
